#!/bin/bash

TAGKEY=$1
TAGVALUE=$2

# recover current ec2 instance id
INSTANCE_ID=$(wget -q -O - http://instance-data/latest/meta-data/instance-id)

# set ec2tags
aws ec2 create-tags --resources $INSTANCE_ID --tags Key=$TAGKEY,Value=$TAGVALUE
