#!/bin/bash

APPNAME=$1
APPGROUPSRC=$2
APPGROUPTARGET=$3
STATUS="Succeeded"

# recover last the last deploy identifier
DEPLOY_ID=`aws deploy list-deployments \
--application-name ${APPNAME} \
--deployment-group-name ${APPGROUPSRC} \
--include-only-statuses ${STATUS} \
--region=eu-west-1 \
| sed '3q;d' | awk -F'"' '{ print $2 }'`

# read the needed data from the latest deploy
aws deploy get-deployment --deployment-id $DEPLOY_ID > /tmp/deploy.json
BUCKET=`cat /tmp/deploy.json | grep "\"bucket\":" | awk -F'"' '{ print $4 }'`
ZIPKEY=`cat /tmp/deploy.json | grep "\"key\":" | awk -F'"' '{ print $4 }'`
LOCATION="bucket=${BUCKET},bundleType=zip,key=${ZIPKEY}"
rm /tmp/deploy.json

# re-deploy the same revision again
aws deploy create-deployment --application-name $APPNAME --deployment-group-name $APPGROUPTARGET --s3-location $LOCATION
